apiVersion: v1
kind: ConfigMap
metadata:
  name: store-simulator-cm
data:
  APP_VERSION: 0.0.13
  APP_TARGET_MESSAGING: kafka,IBMMQ
  KAFKA_BOOTSTRAP_SERVERS: es-demo-kafka-bootstrap.cp4i-eventstreams.svc:9093
  KAFKA_TOPIC_NAME: ahsoka20-items
  KAFKA_SECURITY_PROTOCOL: SSL
  USER_CERT_PWD: none
  MQ_HOST: ahsoka20-mq-ibm-mq.ahsoka20.svc
  # external: mq1-cp4i-ibm-mq-qm-cp4i-mq1.apps.biggs.coc-ibm.com
  MQ_PORT: "1414"
  MQ_QMGR: ahsoka20MQ 
  MQ_QUEUE_NAME: ITEMS
  MQ_CHANNEL: DEV.APP.SVRCONN